"use client";
import React from "react";
import { Button } from "../ui/button";
import { Download } from "lucide-react";

type Props = {
  summaryText: string;
  fileName: string;
  title: string;
  createdAt: string;
};
const DownLoadSummaryButton = ({
  summaryText,
  fileName,
  title,
  createdAt,
}: Props) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}

Generated Summary
=================

**Generated on:** ${new Date(createdAt).toLocaleDateString("en-US", {
  year: "numeric",
  month: "long",
  day: "numeric",
})}

---

${summaryText}

---

**Original File:** ${fileName}

*Generated by AI*
`;
    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${fileName.replace(/\.[^/.]+$/, "")}_summary.txt`;
    document.body.appendChild(link); // Append link to body for Firefox compatibility
    link.click();

    document.body.removeChild(link); // Remove the link element after download
    URL.revokeObjectURL(url); // Clean up the URL object after download
  };
  return (
    <Button
      size={"sm"}
      onClick={handleDownload}
      className="h-8 px-3 bg-sky-100 text-sky-600 hover:text-sky-700 hover:bg-sky-50"
    >
        <Download className="w-4 h-4" />
      Download Summary
    </Button>
  );
};

export default DownLoadSummaryButton;
